---
title: "An attempt at revival"
description: |
  Short poems to revive the lose poet within 
author:
  - name: Janith Wanniarachchi
date: "2024-10-10"
---

# An attempt at revival

Perhaps there is some beauty to life,   

in all the strangers that we cross paths with   
where all their stories inspire us   
where their presence next to us brings a platonic warmth   
where our solemn goodbyes leave a bittersweet smile   

in all the moments of laughter   
where our eyes squint into darkness   
where our breaths fall rapidly   
where the sound of our laughter echoes   

in all the tiny picture perfect nature's paintings   
where we smile dreamily looking at palettes beyond our imagination   
where we reach for our phones to freeze the time, never to look back   
where we inhale and exhale the fragrances that the wind brings   

Perhaps there is some beauty in life,   
even though everytime I find no beauty in life   
each time I consider my demise   
as I wake from my slumber   

# The deafening silence

The only punishment   
the child within me   
knew was   
to be shunned from the rest of the world   
and have no one talk to you   

Oh how the tables have turned   
As I jump between the   
drug dealers on my phone   
begging for scraps of dopamine   
a puff of oxytocin.   
The inner child screaming   
in fear of being punished   
for a crime unknown to both of us.   

To be in the silence of solitude   
one must fall in love with oneself,   
but alas how can one fall in love with a prison   
that they tried to run away from their whole life.
