---
title: "Letters to my child"
description: "Another small experiment"
draft: true
---

I do not know how to structure this. But I want to pursue writing up things that that I learned from my every day happenings as sort of learned lessons for my future child to read and see that life isn't always linear. Everyone is understanding things and growing as they go in life. Perhaps I might merge this with the memoirs of a magpie and restructure it.

Date: 16th February 2025
To: The one after my own heart

The weather is becoming more colder even though it's supposed to be the height of summer. Waking up was hard today as it was a nice cold Sunday morning and the tendency  to just roll over and sleep was too high. I had to promise myself that I would get out of bed at 07:15AM and show up to my laptop and keyboard to write this. 
When we are young promises mean a lot for us. It's a sign of putting trust on to others, and also a way to receive trust on to yourself. When you are young, you will make promises to others and others will make promises to you as well. At first you would expect those around you to keep their promises and at a certain point you will realize that most promises don't take promises seriously. That is where the tendency comes to promise things to yourself but have no serious obligation in your head. That is where the first steps to lying to yourself starts. From there onwards anytime you promise yourself that you would stop doing a bad behavior or that you would start doing a good behavior, it will be hard for you to keep the promise. Because you have seen others dismiss promises and consider them as simple statements, and you have seen how you would promise things to others and not follow through with it. Slowly just like that you start lying to yourself.
It's crucial that you do not follow this pattern. The first step to surviving in this world is to have yourself on your side and for that you need to foster a trusting relationship with yourself. So keep in mind when you make promises to yourself, only make the promises that you know you wholeheartedly can do and if you do make a promise, follow through with it to the end.   
Aside from that, carving out a path for yourself requires a lot I will say that for sure. Right now I am at a place where I need to stand strong on my idea and push forward with it while taking in the feedback of others in a healthy manner. It's rough I must say, but it is necessary for us to be able to form an opinion of our own. It can be a struggle to find a solid foundation to rely on but do not let that discourage you. As long as you learn how to put your effort in at the right time and to go with the flow the rest of the times, it can be a lot easier to navigate. When is the right time to put in the effort and when is the right time to go with the flow. Well my dear, I wouldn't be able to find that answer for you. Only advice I can give is to listen objectively. Listen to your body objectively, listen to others objectively, listen to your mind objectively. Your body can rarely lie but your mind and those around you can. Ask nicely and your body shall respond.

Date: 17.02.2025
To: The one after my own heart

For some reason falling asleep when needed is a lot difficult than it may seem on the surface. I always wonder what people think about when they fall asleep. Do they think about their loved ones? Do they think about the day to be conquered tomorrow? or the day that they regret today? Do they think about the dramas and plays that they witnessed in the day itself? I will not know for sure what others are thinking, for me I try my best to picture you as best as I can to imagination. If ever you doubt whether you were the same as I imagined the answer will always be, no, you were better than what I always imagined.     
There's always an enjoyment in progressively getting better at things and finding out new things to be good at is always fun. Perhaps one of the best reasons to do something is to do it because it is good for you and doesn't harm those around you and you can keep on doing it into the future reaping the benefits of what you sowed. Might not seem motivational but in most cases whatever reason you hold on as the motivation has a tendency to either change drastically for the good and for the bad. In some cases you might realise that the reason that motivated you was not actually a healthy reason to be motivated. If you ever come across a moment like that my dear, just know that it's a feeling that I experienced quite a lot in my life. The first thing you must refrain from is beating yourself up and doubting all the progress that you made so far. When a foundation that you stand on gets taken out from you, you need to have yourself on your side first and foremost before anyone else joins your side. While the motivating factor might not have been suitable, progress is still progress, and mitigating the damage will take time and patience, but now that you have a clearer mind and a loving self, the future is going to be brighter I promise.    
Also if ever you come across something that ignites a childlike smile in you, go experience that. I can guarantee you, there will be a brief moment of euphoria and after that whether or not you continue feeling it every time will be questionable but it will be a lovely reminder for you to love the inner child within you.    

Date: 18.02.2025
To: The one after my own heart

Well it seems I have been bested and my ego is shattered. I thought I was right and the ideas of others were wrong. It might be the case that I can be right and wrong at the same time while also having the others be right and wrong at the same time. This is where I guess the notion of such cut and dry dualities become gray. It also could be that I am too proud to accept that I thought wrong. It might not be surprising to you my dear, to hear that your old man was a proud person. Nevertheless, I will accept this defeat with dignity. However, there's more to the story now that I made this tiny progress in the research. As to where and how the story will go is still a mystery to me as well.     
A surprising comment caught me off guard while I was having a chat with a friend of mine. "I wouldn't want to share my eggs and cucumbers with anyone yet." It was interesting  to think that being single gives you this freedom to pursue life in a way that is completely within your control and definitions. You might also come to an age and wonder "why should I give up being single for someone else?". And truth be told at the age that your old man is at now, he has no idea either. Although I must say I do fall easily for people but that is because I tend to forget the freedom that I take for granted. Perhaps with the right person it shouldn't feel like the freedom is taken away and maybe it feels a lot like there's a bit more color to the monotone freedom in your life.     
Is life simply a never ending cycle of having something and taking it for granted and then losing that said thing proceeded by an eternal fight to gain it again only to lose it after taking it for granted? Perhaps, that might be the case. As Zen Buddhists would say at your purest form your mind is said to be calm and free and yet we introduce so many other things that bring in a series of pain and suffering.      

Date: 19.02.2025
To: The one after my own heart

Working early morning does help it seems. I actually made some progress in the work that I was doing and to be honest it felt a lot more lively and less stressful than working late night. Something about me is slowly shifting I guess, and I'm glad that shift is happening. For you my dear there will come a point in time where you will be working all night long and still be able to function properly the next few days. Cherish those moments, because with time that skill becomes harder to maintain. Despite what people might say about playing to your energy levels, working late would be a bad idea if you have a bad history with it as your old man does.    
Speaking of bad history, I'm still not ready to fight back against the bullies within the walls of my family. I hope to god that by the time you are reading this I have either fought back or the bully had let go of their ways. Either way I have strengthened my resolve when presented with snide remarks of my self image by knowing that I look good to myself regardless of whatever happens to my self image. If my dear someday you want to love someone unconditionally, first love yourself in a way that no matter the mistakes or slip ups that you have that you will love yourself in the same way no matter what.
In other news, your old man may appear tough at times but know that he would cry over stories told in the big screen easily. Perhaps the most poignant set of events that affects me is the case of the misunderstood person shunning himself from the crowd and not being able to face them is able to face them with slow build up of courage. Perhaps there might be some link to my social anxiety or perhaps it's something deeper within me that finds this connection. Even though I might appear as someone who would always talk and check up on people, internally I too am scared to talk to people sometimes. It takes a bit of effort on my end to talk to people because of a variety of reasons sometimes.
It can be scary to be on a journey alone. For me whenever I see the stars at night I find companionship with them, where I would be greeting Orion and mapping out the rest of the night sky in reference to Orion. On some days it is mapped out through with the centaur. Have some small moments of whimsy in your life. See the beauty in the ordinary by letting go of your preconceived expectations and experiencing the moment fully. It might be a small flower blooming in between the rough concrete or it could be the traffic lights turning green in front of a tapestry of velvety clouds.
Carving a path for yourself can be scary at times. But at all times what's necessary is to understand what your strengths are and hone them. You might not know what your strengths are, the people around you might not know some parts of it, but there is always the case where you might have strengths that haven't been explored at all or didn't have the right time and guidance to be your strength. Whatever it is know that every step you take will be helping you reach a place of satisfaction, because surprisingly we get to decide where our place of satisfaction is at.