project:
  type: website
  output-dir: _docs

website:
  title: "Janith Wanniarachchi"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Talks"
        href: talks.qmd
      - text: "Blog"
        href: blog.html
      - text: "Creative Corner"
        href: creatives.qmd
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/janithwanni
  google-analytics:
    tracking-id: "G-8F5XVPT9G2"
    anonymize-ip: true
  cookie-consent:
    type: express
    style: headline
    palette: dark

format:
  html:
    theme:
      - litera
      - main.scss
    toc: false
