---
title: "The usual place?"
description: |
  A poem written to reignite the passion that was once lost 
author:
  - name: Janith Wanniarachchi
date: "2025-08-01"
---

Despite the stinging cold weather at my heels,   
I step out of my humble abode,    
in the hopes I will get to see you.    
The moon is shining bright outside.     
I ask her whether she saw you,        
going into the place I was headed to,     
for I already knew that you lived in my heart persistently.        
The moon shrugged at me,
shaking a tuft of gray clouds away,
shining brighter to guide me on my journey.

And so I begin,     
my hopes growing with every step.        
My eyes are wide open with excitement,      
yet I am dreaming of seeing you,     
as I open the door to the restaurant.      

Dreams and reality meld,      
as I open the door and from the sea of faces,       
I see the back of your head.      
You move between each table smiling       
carrying an immense load of plates on your hands,     
and the weight of the world on your shoulders.     

My day is made,       
words matter no more,    
only the flutter of butterflies in my stomach speaking in my place,    
as I see you beam at me in recognition.      

_"The usual place?"_ she asks,        
and I say _"yes please thank you"_ enthusiastically.     
Knowing fully well,      
my place in your life never changed,     
from the moment I stepped through the door.     
Even though for me she stepped in,       
from her workplace,        
to my mind,       
and then to my heart.      

