---
title: "Loving you is like being on a swing"
description: |
  A poem written to express my feelings towards her 
author:
  - name: Janith Wanniarachchi
date: "2025-12-18"
---

We used to love going up and down on a swing.      
Is that why when I think of loving you,    
my mind goes up in elation     
thinking of how beautiful our life will be.    
And then slowly swings back to despair     
thinking of how painful connecting our lives will be.     

_"My heart skips a beat when I see you"_     
_"Butterflies flutter in my core"_     

All these cliches,    
and yet I feel none of that with you.      

What I felt with you     
shattered the rigid marble box     
that I kept the meaning of love in.     

I used to think that,    
Love is based on chemistry,    
Love is based on first sight,     
Love is based on the fire that they light up in you,     

But truly,     
To be loved is to be a witness and to be witnessed.     
And what a subtle gentle feeling it is,     
when I'm with you     

I yearn for you       
With every flower that I photograph       
With every breeze that cools my scorched skin       
With every shard you painted in my heart of glass    

Everytime I witness my life     
you step into my mind gently.
And I pour my heart out to you      
in hopes that you will be my witness    

Despite my yearning,    
I can never be able to get out of this swing,      
and step on to the ground with you.     

For I know that,     
right now is not the right time,      
and us miles apart is not the right place.   

Yet despite all odds,    
I know that,    
us healing together is the right journey,     
for both of us.    
