---
title: "Actions can be too loud"
description: |
  A poem written to find the last missing piece in a puzzle 
author:
  - name: Janith Wanniarachchi
date: "2025-12-03"
---

"Actions speak louder than words""    
and he was never taught the word love.    

He did not know that    
he could love himself    
for ever since young    
he was told that    
he was not lovable or useful     
he was disgusting and unapproachable    

But he _did_ know that    
he needed to show his love for others      
so that they would stay    

So he loved others with gifts     
by being their ride or die,     
by checking up on them,      
by cheering them on,       
by dedicating his time, money and energy.

But he did not know     
how to say the word love      
to any of them.

Meanwhile he gave himself the bare minimum      
in food, in shelter, in care,    
and when love and reassurance was needed      
he simply spoke with the loudest actions      
by buying fancy gifts     
by indulging himself of substance    
by reaching the climax     
of either his senses or his accomplishments      

For actions were louder than words    

The thing with actions     
is that actions are loud.     

And every time words were not said     
the silence had to filled by actions     
that were louder and louder.     

As his hearing slowly fell apart     
no one's words could cross his ears anymore     
not even his own words,
and only actions could.        

But the louder his actions got      
the more tired he got.     

<i>
In the end,     
my little one,     
You need the softness of words       
to gently tell the truth.     
</i>
<i>
For if you can't speak it     
how do you know     
whether your actions are speaking     
what you want to say     
</i>
