---
title: "7 days of writing"
description: |
  An attempt at writing short stories based on a random prompt within 30 minutes everyday for 7 days
author:
  - name: Janith Wanniarachchi
date: "2021-10-05"
output:
  distill::distill_article:
    self_contained: false
---

## Day 1

Prompt: _As he flicked through the letters, a small, handwritten envelope caught his attention and his heart began to thump._ 

The bright silver colored wax seal glowed in the light contrasting the scarlet envelope in his hand. "Today's not the day for this" He sighed and kept the envelope away. As he continued on going through the letters that were sent to him after his wife's death, the crimson letter still begged his attention no matter how hard he tried to ignore it. As a soft siren call, the letter was moaning to be opened and release the words held within it. "I'm not ready for you right now, love." He whispered softly as if the envelope could hear him. He engrossed himself in another letter, one that was more interesting than the rest, which wished him good health in the times of crisis that he was in. All the other letters were one big combination of pity and bitter resent for his unfortunate loss. Only a few addressed his declining mental health after the funeral, and he feared those who did. It was as if they knew the reality and were mocking him instead. How dare they? They didn't have to do this to him. The scarlet envelope also joined in the mockery with the name "Mrs. Hoffman" glinting in the light above the silver wax seal. Shaking his head, he began writing down a reply to one of the letters he recieved. "Thank you for your condolences, it was quite a shock to me when I heard that my wife, Mrs. Hoffman died from food poisoning. I assure you, I am taking the best care of my mental health since the day of the funeral. I have given my statement to the police as well about who could have murdered my dear beloved wife, but so far the investigation has been inconclusive." A huge laughter broke his writing, which seemed to have come from the scarlett envelope on his desk. He must have imagined it. Even in her death she knew perfectly well when he was lieing, otherwise how would have she sent this letter to him three days after her funeral.

## Day 2

Prompt: _She had enjoyed ten years of being totally irresponsible._ 

And those were the most blissful ten years of her life. It was an era where she was free to do what she wanted and get whatever she wanted as many as she wants. She was enjoying her rights without the reponsibilities. It was utter bliss. Now looking back on all those times, as she was sitting on the floor of her one bedroom apartment sipping a cheap bottle of wine as her sole dinner, she couldnt help but feel miserable for all the regrets that she had piled up inside of her. "Yep, that's the cue for more wine" Her brain automatically jumped into her safety route with her hand searching for the bottle and the glass to pour more wine. "How did it all go wrong for me? Life was so damn amazing for me?" Her mind wandered enough to ask, and just like a tyrant suppressing the media, she quickly washed off that thought with another huge gulp from her glass. "I really should get my life back together." One more gulp. "This isn't going to workout for long. I used to be better than this honestly. I need to get back on track with everything that I left behind." Three huge gulps. It was useless. The wine was a finger in the dam about to be broken apart. All the pent up feeling of regret and bitter resentfulness was piling up threatening to explode and her wine couldn't keep it back any longer. "I can't face all of those things right now. I need some time." she spoke to the empty room with the mattress on the floor. "If not now then when?" Her mind whispered back as her eyes began closing in extreme drowsiness.

## Day 3

Prompt: _Without meaning to, she'd arranged two dates for the same evening._ 

And just like that the stars aligned to unleash the titans kept trapped underneath. The day that she had been waiting for had finally arrived. The day that she get to spend some time with the guy from her art class. He was everything she wanted, and he was giving it consistently with no compromises. Most men promise to give the world to you at once but in reality what women want is the world a drop of the ocean at a time. Consistency is key. Any woman who had to suffer a man going down her in inconsistent rhythms can scream in agreement for that statement. If only men paid more attention to those details in their everyday transactions. It all starts off with a small detail being lost in one day and it snowballs to the entire beauty of it being tarnished by a souless ice cold gesture. Sadly that is how marriages end, in most cases that is. A spark would not be needed if there was no ice cold feelings between a married couple. "Sigh, if only men could understand these things" She sighed to herself as she checked herself in the mirror. Her lips were highlighted with a light shade of pink that complimented her brown skin and her hair was let down in the best possible way that she could manage as it draped over her strapless red evening gown. As she stepped on to her car and drove to the restaurant, her mind was still seething with the absurdity that men could be so dense. For all they could know, the house will slowly start to crumble down into pieces and they slowly sidestep off the rubble and go on their way as if nothing happened. "If the man of the house can't fix a house then you might as well get a builder to repair the damages." She scoffed as she slowly arrived at the restaurant. It was when she arrived at the gate of the restaurant that she realized the titans that she had unleashed. Two men were laughing and chatting in loud voices. One of them was her date for tonight, the guy from her art class that gave her the world one drop of the ocean at a time and the other was her husband who gave up giving her the world halfway through.

## Day 4

Prompt: _They had to make sure that none of their colleagues noticed._ 

The professors and the students were all gathered in one place with soft music, drinks and food for everyone. The entire college hall was brimming with people and a clear separation can be seen between the two crowds as the teaching staff took a corner of the hall and talked all about the good old days and watched the students from afar, while  the students took over the entire hall. The dance floor was bustling but his head was not into it not after what happened last night. It was the amazing night of his life and it was the person that he loved the most. The world around him looked bright and colorful after that night with her. And looking at the corner where the teaching staff was gathered, he could see her again from afar laughing and talking with everyone else. The way her laughter made her eyes wrinkle and the musical notes that her laughter creates is heavenly to him. His staring must have been sensed by her as she turned to see him and smiled. There was nothing more that he wanted in this world than to wake up to that smile everyday just like he woke up today. "Yo Mike, what are you doing sitting over there mate? C'mon there's an entire party going out here." Joshua shouted from amidst the crowd and he decided to inch his way towards the middle to avoid any suspicion. He acted as if he was dancing when in reality he was just dancing along to get glimpses of her smile. "Dude the fuck do you think you are doing dancing around my girl?" Joshua shouted from afar as he charged against him. "Bro bro it's a misunderstanding I wasn't grinding against your girlfriend mate." Joshua started racing in hands in defeat hoping they would be able to stop the raging bull. "Yeah Joshua I didn' t even know he was here. Quit yapping about guys grinding against me when you aren't even here to dance with me" His girlfriend retorted and walked away with the rest of the girls. "Babe no.." Joshua mumbled and glared at Mike as he ran after her. Even through all of this commotion his eyes sought her out and he could see her giggling like a school girl and shaking her head at his embarassment. He couldn't help but laugh himself. And a moment later his heart sank as she grabbed her bag and headed out towards the door. It was way too early to leave the party now which made him question whether he did something wrong to make her angry. He was now torn between two choices, should he run after her or give her the space she needs. "Screw this" He muttered to himself and ran towards the exit. He needed her. More than anything in the world. Outside he finally caught up to her as she was standing near her car staring out at the stars. She turned as he approached her and smiled to him. "I was wondering when you were going to arrive" She laughed and in an instant his entire world was her laughter. "You could have dropped a text you know?" He said while playing with his hair. "Well I really didn't want to bring my phone here to steal my time with you." She whispered and the look in her eyes told him all that he needed. "Get in the car, we are going back to my place." she winked and jumped in to the car.

## Day 5

Prompt: _Was it simply luck that had caused her to turn down this street?_ 

Whatever it was, the god's above had definitely answered her prayers. She was going through a rough week  the past couple of days and she really needed the comfort that she was about to receive. The moment she saw him, it was all over for her. His bushy moustache and his curly hair, took her back to her childhood when she secretly enjoyed the things that were forbidden in her house. His smile beckoned her to come closer to him. At that moment all her problems vanished away and she was the happiest girl in the world. She didn't care even if she took this to her bed and went down like an animal, succumbing to her carnal pleasures, no matter what otehrs would think of her actions. It was all that she wanted at that moment. To feel fulfilled to the point of whispering "oh my god" and moaning with every moment passing. She was already feeling herself becoming wet as she drooled remembering the mouth watering sensations she had felt. Kentucky Fried Chicken. The huge sign of that old man smiling was all she needed as she remembered how much she wanted to try out their new deal for hot drumlets. Pressing the gas on her vehicle she sped up to the drive through and she ordered all the hot drumlets her heart desired. Just as she imagined just the scent of the chicken made her sigh in relief. She needed a hot drumlet break all along, and she finally got it.

## Day 6

Prompt: _She had made a poor job of hiding the damage._ 

It was not her best day to begin with even. Her finger was wrapped with a small plaster to stop the bleeding but the kitchen sink was tainted with tiny drops of blood. This wouldn't have been a hard thing to do if her mother was around to help her out. But it was her decision to move out and start a new life outside her country. "Well I won't be able to make the mac and cheese anymore at this rate, unless I want to substitute the ketchup with my own blood." She sighed and began cleaning out the blood stains and gathered the untarnished cheese gratings and poured them to her macaroni to finish cooking the mac and cheese. This was more of a macaroni with a side of cheese rather than a complete mac and cheese like what her mother used to make. After wrapping her food up she managed to get into her sofa and turned on Netflix to eat her dinner while watching some mind numbing tv shows. At that moment she heard the bell of her apartment door ring. Swearing to all the gods out there and the person who decided to ring the bell, she trudged over to the door. Opening the door it was her neighbour, the young man from her home country standing infront of her wearing the cutest shirt that brought out all the curves in his body. "I heard a scream earlier and I wanted to come and check up on you. Are you doing all right?" he said. "Oh no it's nothing I'm completely fine.." her words were interrupted as his gaze fell on the finger that had been plastered. "Ah so this is what caused it. What were you trying to make? I smell cheese inside here." He said taking a look around her room which made her sweat intensively considering how messy her room had been the past few days. She could feel all the judgement falling on her and she mumbled "I was making a mac and cheese". As soon as the words left her mouth his eyes lit up and said "What a coincidence I also made mac and cheese! Do you want to come over to my place and have dinner together? If you don't mind" He said excitedly and for a moment she wasn't sure. Was this an invitation to have sex? or was she being genuine. It's highly unlikely this guy has any feelings for her considering how short and pudgy she looks. She herself didn't have any feelings for the guy and considered as a friend only. "Yeah sure, I will come over there. Let me put on something better than this." "Oh no need at all! It's just a friendly dinner and besides you look really cute in your outfit." He said with a smile that made her instantly realize "This guy is completely blind and stupid isn't he? to think that I look cute in my home wear."

## Day 7

Prompt: _There was a legend about the well in the garden._ 

No one really knew where the well was, but everyone seemed to talk about a well in the garden. On his first day as a servant in this grand mansion he never knew what they meant by this well in the garden and he dared not to ask in case people might think he's not that educated. He searched every nook and corner in the garden but there was not even a sight of a well. The only place where a well could possibly exist was under the oak tree at the centre of the courtyard and unless he topples that tree over he will never know of it. Frankly he didn't know why he needed to find a well. No one told what was in the well, other than well, water. With no other options he tried his best not to think about the well in the garden, but he couldn't no matter how hard he tried. And he decided to start from the corner of the garden and inspect one last time. This time he followed any trails of dampness in the soil and soon he realized the trail was taking him in circles around the oak tree or in general the garden. With no other option he had to give up and realize that maybe the well in the garden was right under the tree. But nothing changed now that he knew where the well was upto a certain extent.