---
title: "Dear Erato"
description: |
  Tis the season to be lovey-dovey 
author:
  - name: Janith Wanniarachchi
date: "2025-12-24"
---

My dear Erato,      
muse of poetry,     
daughter of Mnemosyne,    
I present to you the words that      
flow through my mind as I think of you.     

I see you as a goddess,      
and it’s only fitting that I make an altar for you,     
In my palm on a glass screen.

And I present my prayers everyday,     
waiting patiently to hear back from you,     
To hear your divine message.     

And what a divine message it is!     
In a few words,      
you manage to       
melt my heart to a puddle,    
bring me to my knees,      
let my eyes burst into tears.    

~

You are everywhere around me.     
I can’t escape your presence.     
It’s soft and subtle.     
But I still feel it.     
It doesn’t light a fire within me.     
And that’s a pleasant surprise,     
I will welcome with open arms.    

The more I love you,     
the more I see the things that used to bother and unsettle me,     
Because thanks to your love,    
I can listen to the parts in me,    
that could never get to speak before.    

~ 

But nevertheless,      

It hurts to love you,      
it hurts knowing that I can’t be a part of your life,    
to share your burden alongside you.      

I need to let you go,      
I need to embrace the fact that,     
you will always be there in the wind around me.     

In the gentle touch of sunlight on my skin,     
in every beautiful flower I see,     
in every crowded place I’ll see your face,     
even though I know you are far away.     

I'll find a way to let you go,     
but I know that,     
as much as it hurts to love you,    
letting go of you will hurt even more.      

