---
title: "Adam's Tale"
description: |
  A short story written Live on Twitch
author:
  - name: Janith Wanniarachchi
date: 2020-06-08
---

## Prologue 
(FINAL BATTLE BETWEEN MB & OPPOSING THIEF CLAN)   
“Breathe in, breathe out”. He whispered to himself, as he gripped the staff in both of his hands. He was trembling as he pointed the staff up at the red glowing eyes within the hood of the man that was standing before him. The red eyes gazed upon him, and there was no chance of reading any emotion from that darkness within the hood. He pointed the staff up at the hooded figure, and took one deep breath, before whispering loud enough for the figure infront of him to hear. 
“You took away the family I was born to, but I won’t let you take away the family that I’m a prisoner of”. 
For a second the glow of the red eyes dimmed as he raised his staff once more and brought it down on a sideway arc on to the shoulder of the figure. With swift reflexes, wood and steel met each other in a dull thud followed by a screeching scrape as the two opponents disengaged. 
And so began the dance of two minds and bodies, as they started to circle each other, waiting for an opening to strike and bring peace to the night. 

## Chapter 1   
“Harder, Adam, Harder!” That was all that he heard as he began punching left and right to the cotton dummy in front of him. The sensation of fist colliding with cotton registered in his head, but his mind was scattered as his blows slowed to a stop. 

“Adam, if you believe I am going to let you go in such a state as a warrior monk, you are fooling yourself. Do you want me to demote you to where you started from and make you practice breathing in and out again.” The words demoting fell on to his ears and within a split second he became aware of his situation. 

The cold wind from the open doorway of the training ground brushed against his light robes. But the heat from his arms and his sudden realisation of the possibility of him being demoted ignited a warmth within him. His eyes followed the direction of the commanding yet steadfast voice and met with the unwavering glance of the chief monk, Zalko who was residing over his training at the temple of Leung Kai. He heaved himself up from his slacking stance and looked straight back at the cotton dummy in front of him. And as he let his mind settle into a state of flow, the cotton dummy brought back all the memories that he had kept inside within him. -He found the temple along his journey to strengthen himself after he lost his parents.- From his first day as an initiative of the temple, he had long stood in the middle of the training ground and practiced his breathing all the while staring at this same cotton dummy. 

Now the dummy is beckoning him to prove himself after years of practicing his breathing. He took his opening stance and immersed himself in the reason behind his training. The core memory where his mind was in complete clarity. 

_let’s make a present and past mixing kinda thing. Adam will do a certain action and that will trigger a certain key sensory input from his past which will ease in the reader as to what has happened to him to end up here. And we will end it with Adam delivering the final fatal blow to the dummy and in the past key memory he remembers the person who did that and the sound of his parents falling down. MAKE THE PAST SEGMENTS IN ITALIC IN THE FINAL BOOK_ 


It was in the rivers of his village as he lied down to rest on the riverbed, moments before his village was raided. 

Adam took his first step forward from his stance. 

> First it was a soft thud that he heard when the branches of the yew tree above him rustled as if an animal jumped on to it.  

His eyes narrowed down on the cotton dummy covered in brown leather right in front of him. 

> Then it was two more thuds as he watched three dark brown figures jump their way towards his village.   

His breath quickened as he advanced quickly on the dummy. 

> He was panting as he was running towards his village to alert the chief about these creatures.   

With a soft exhale he swiftly delivered his first blow across the ribs of the dummy. 

> He watched as the first sentry of his village topple down from his sentry post. And yet no one except him noticed his choked scream muffled with the sound of his crashing bones.   

He took one long breath and delivered seven more blows to the key points of the dummy. 

> One by one they fell and all that was left to protect the village was the chief.   

After the seven blows his breathing slowed, to concentrate on the heart of the dummy. With a graceful fist he delivered his final blow to the heart of the dummy.   

> And that too was gone, with the dull thud of the chief’s body collapsing forward with a blade protruding from his back. And in his place stood three cloaked figures.   

His gaze met with the hollow eyes of the dummy. Black, depthless and unforgiving. 

> The cold steel of the double bladed scythe glinted in the horrified villagers eyes. But the shadow of his parents blocked the gleam of fear from entering their eyes as they stood as the last shield for the village.  

He took one last breath, and brought in all the pain and anger he had. 

> The double bladed scythe shone in the moonlight and changed colors from silver to crimson as the two bodies crumpled to the ground.   

Years of training in mastering his pain and anger, and he finally let go of his emotions. All that he had bottled up inside swam through him and he became one with his ambition. With one last battle cry he delivered a fatal punch to the dummy’s head. Just as his parents fell dead to the scythe of one of the three thieves that raided their villages, the dummy’s head fell clean off from its body and rolled over towards Zalko’s feet.   

The sound of the broken head rolling was deafening in the silent practicing ground, but for Adam the only sound he could hear was the sound of his heavy breathing. He gathered his thoughts, by pushing them down towards the back of his head, as he always did. His gaze quickly went towards Zalko, to confirm whether his final display of strength was able to convince his master. On the other end of the practicing ground Zalko was staring at the broken head near his feet and didn’t move for a long time. 

“Well? Did I pass the test?” Adam finally asks with no regards for the traditional respect that entails the end of a test in the temple of Liung Kai. Zalko slowly raises his head to look deeply at Adam. It was then only that Adam gained awareness of where he was and what he was doing at that moment. He brought his palms together and bowed and whispered “Master, I have completed my training, have I mastered the ancient ways of Liung Kai, the first of his kind.” It was a phrase that he had memorised for a long time everyday when he envisioned himself becoming a true warrior monk of this temple. 

“You have completed your training young initiative, come with me and take your birth right as a new warrior monk of the temple of Liung Kai”. Zalko whispered softly with his gaze fixated on him, but his eyes seemed quite distant at the same time, as if he was lost in thought. Zalko turned around and began walking towards the main shrine of the temple. Adam let out a sigh of relief, but his face never showed a smile. He adjusted his robe and slowly walked behind Zalko. 

The main shrine was a few feet away from the training grounds and was the main area where monks held their rituals. As he was walking towards the main shrine, his gaze met with the peach trees that lined the pathway and his thoughts went back to where he started from. Adam had entered this temple through the words of his previous master, the village Swordskeeper. The swordskeeper was like a father to him as he taught him all that he knew about swordsmanship. He also had learnt from the temple of Liung Kai, but he couldn’t make it to the end and become a warrior monk. He had guided him and prepared him for what would he have to face inside the temple, but even he couldn’t prepare him for what was about to happen next. 

His train of thoughts was disturbed by the creaking noise of wood grating against iron, as Zalko opened the door of the main shrine before him. The first sense that overwhelmed him was the smell of stale air that had been kept locked for ages. “Hasn’t anyone become a warrior monk in a long time?” Adam asked while trying his best to breath slowly. “It has been ages since a warrior monk has proven his skills in this temple. Mostly because no one ever persevered long enough to take up the final task. The ways of Liung Kai is different from other temples, as our great ancestor himself believed that students of this temple should rigorously follow the fundamentals of breathing and staying calm in the most stressful situations.” Zalko said calmly as he walked around opening the windows of the shrine to let in the cool November air in. Adam took in all that was around him and realised that he was standing in the midst of a room full of statues and weapons mounted on the walls. From clubs to hammers to whips and staffs and finally ending in broad swords and long swords, the entire wall of the shrine was a monument to all the fighting styles taught in the temple of Liung Kai. 

“Traditionally, a warrior monk of the Liung Kai receives double short swords as his parting weapon from the temple.” Adam suddenly realised that Zalko had been talking to him all through out the time that he was staring at the weapons. “Yes master” Adam whispered in a calm tone bowing down to show his respect. He was eager to receive the double short swords as his parting gift and continue on his true journey. His face showed no excitement as he knew what his true aims were. “However, it can also be the case that the master of an initiative can decide whether to give him a different weapon as a lesson for him to grow.” Zalko said gravely as he stared down at Adam from the other end of the shrine. 

Adam stared back at Zalko’s eyes, trying his best to keep his shock away from his face. It was a skill that he had to learn the hard way from the day his parents passed away, where everyone was trying their best to coax him out of going after the thieves. “Never let your face tell your true mission to anyone” Those were the words that the Swordskeeper of the village told him, whenever he showed anger at the mention of great raid. 

“As you wish master, I shall gladly accept your words of wisdom.” Adam said once again bowing slightly. **“Adam, heed my words, and I need you to do more than just accept them. Do not try to douse a burning house by embracing it with your whole self. In the end the house will always perish, but if you firmly hold on to your embrace on the burning house, you shall also join the ashes of the burnt house.”** Zalko whispered softly to Adam, and for a moment Adam could see a slight hint of worry in his brow. Adam nodded deeply and said “I understand master, my teachings from this temple will help me a lot in dousing the flames of the burning house” Adam whispered in a reassuring tone. Zalko’s brow furrowed even more at his reply and in a flash of a second all traces of worry vanished from his face, replaced by a simple empty expression. With a soft nod he walked towards the farthest end of the shrine to pick up a long object from the wall. 
“You are still far away from understanding the true nature of your own self. I believe the lesson that you have to learn, will be completed through the help of this weapon.” Zalko brought forward to him a wooden staff that was as tall as he was. Adam could not hide the shock anymore as he let his mouth gape open at the sight of the wooden staff presented to him. “This is Pasindir, it’s a wooden staff with heavy metal weights on either ends. As you can see there are three rings on each end, and each ring has heavier metal towards the end.” Zalko let the staff roll off his hands and Adam caught it a moment before it hit the ground.  As he straightened up, Adam was able to hide the shock that was in his mind. His jaw was clenched in anger, and his fists gripped the staff tightly as if he was trying to break it into two, just to show Zalko that a mere toothpick can not help him in his mission. He had wasted months on training in the hopes of getting the coveted short swords, and now he had been presented with a simple staff and a lesson to learn out of the temple. He bowed once again deeply, deep enough to show his gratitude in a sarcastic way. “Thank you master, I shall cherish this gift with a lot of gratitude.” Every word that came out of his mouth dripped with sarcastic anger. “Remember my words Adam, warrior monk of Liung Kai, do not burn yourself trying to douse burning houses.” Zalko said softly as he began the preparations for the ceremony.   

_To be continued_