---
title: "Get Back"
description: |
  Love the demon within you
author:
  - name: Janith Wanniarachchi
date: 2020-06-07
---

He fell again   
He lost count on how many times   
He stared at the bicycle   
Was it his fault that he fell?   
Was he naive to believe   
That he would make it through?   
Was he mad to believe   
That he would be happy in the end?   
Was he ignorant to believe   
That it wouldn’t hurt no matter what?   

Or was it the fault of the road?   
Never smooth where he rode   
Always a bump every day   
That sends the bicycle   
Flying out of control   
Somedays he makes it through   
And somedays the bicycle decides his fate   

Or was it the fault of the bicycle?    
He changed it once before    
He had grown attached to the one before    
And the pain of letting go was too hard    

Maybe the fault was in the thought    
That he could learn to ride    
Maybe the bicycle and him weren’t meant to be    
Maybe the road was best walked upon    
Maybe he hurt himself by riding a bike   
Because he didn’t want to hurt himself   
By always trying to let the bicycle go   
Every time he changed the bicycle   

