---
title: "The compass"
description: |
  A short story I wrote in hopes of practicing voice acting a story
author:
  - name: Janith Wanniarachchi
date: "2021-11-05"
---

It was a chilly night in the bustling city of Vasco. The shops and windows that were wide open in the morning were now shut and dark. The street lamps brought an eerie blue light on to the muddy roads. Snow was falling faintly with a slight breeze adding in to the cold gloominess of the entire city. 

Amidst all of this, a man was walking among these streets tonight. His stride is purposeful yet his glances showed hesitation and fear. But the only thing to fear at a time like these were marauders and animals and neither of them were reported in this area for a long time now. 

He hugged the black coat even closer towards him as a chilly breeze swept past him. The snow was spreading the mud all around the road leaving his boots gathering more brown than black. His gloved hands went inside his coat pocket to fish out a pocket watch made out of silver. With a simple flick he opened the lid of the pocket watch to peer inside. The frost has crept into the glass on the inside and with a delicate gloved finger he brushed the frost away to look at the time. 15 minutes past 8 in the night. He ran a finger delicately over the edge of the  pocket watch watching how the clock began to imitate his fidgeting glances. 

“This is going to be a long night” (He whispers to himself with a sigh.)

This was a time where many went to their beds after working all day long and for some it was the time they were awake after spending their entire morning in bed. 

Yet now was the time that he had to be the most vigilant. His pace slowed down to a halt and his fidgeting glances only increased in frequency. 

“One, Two, Three, Dang it, did I count that lamp again?” (He angrily says this) 

He began counting the number of street lamps from the start of the lane he was in. Only a couple of houses were nearby and all of them were pitch black with no light inside. 

A sign up ahead of him read “Crossroads lane”. 

The location seemed correct and the time was right as discussed. 

“Where the hell is that bastard?” (he said under his breath). 

As if on cue, a cold breeze swept through the road he was in. He readjusted his hat and brought his coat closer to himself. The cold breeze grew in intensity until the snow was falling thick to where he was standing. The air around him thickened and his vision was clouded by a fog that wrapped around him. Out of the foggy white smoke, a pale figure came forward. 

The figure was dressed in silky ephemeral robes of white, with a dimly glowing ring of blue fixed around his forehead. His eyes were not visible as his face was covered in a mask. 

It was a peculiar mask. A mask with no facial expressions, a mask without a mouth or nose. It was the mask worn by the Unforgiven. The symbolic duel ended scythe was tied to his back, as the ice cold steel glinted in the moonlight.

The Unforgiven came forward and stood a feet away from the man in the cloak. With a nod the man brought forward a small wooden dice. The Unforgiven smiled from the corner of his lips (and whispered) “Is that all you can bring as ransom for your daughter”

“You wouldn’t have thought lightly of what I’m parting with, if you knew what this can be used for.” (The man replied in anger)

“Pathetic. You actually thought you are more educated than an Unforgiven. I know what this dice is capable of, and I know when and where it was made. What this dice can do, I can easily do by myself. I have no use for a mere fortune telling dice. We are the Unforgiven, we were not forgiven for knowing everything needed and unneeded. I don’t think this will be an enough ransom, Mr. Randy” (Disappointed tone)

“Please, don’t do that, please, I want my Lizzie back. Oh please don’t do anything to her, I beg you.” (in a crying tone)

“Do not worry, your daughter is in the right hands, no harm shall befall her. If you want to rescue her from our efforts and help, then by all means bring forth a ransom that is worthy of the amount that I told you earlier, Mr. Randy. I shall give you one more chance at redemption, but if you fail next time, I will make sure that my Isilgar shall leave an unforgettable kiss to your neck.” (chuckles lightly) 

The Unforgiven brought his double ended scythe, Isilgar to the Randy’s neck in a sweeping motion and lets it rest there. Randy gazed into the empty mask of the Unforgiven and nods, feeling the cold blade graze his neck. 

“Good day to you Mr. Randy, I shall carry the message of your incompetence to your daughter.”(grim tone) 

In one swift click the Isilgar was back in its sheath, and the Unforgiven took a few steps back. Randy stared in horror as the mist started to cloud his vision and the Unforgiven was no more. 