---
title: "Love thy demon"
description: |
  Love the demon within you
author:
  - name: Janith Wanniarachchi
date: 2020-06-08
---

A darkened cave   
Is all I see   
The floor is moist   
Cold hard rock   
My arms are shackled   
Cuffs tearing   
Pain is searing   
Bare naked   
Vulnerable and exposed   
He walks forward   
A faceless figure   
Never will I recall his face   
For only through a mirror   
Can one see his own face   

“Welcome back   
You worthless scum”   
A voice so calm   
Piercing to the bone   
“Did you really think   
That your life made a difference”   
Laughter of mockery   
A thunderous slap   
Red hot pain   
Seeping through my cheek   
“How many times   
Have I told you   
No one “   
A punch to the gut   
“Will notice”   
A punch to the chest   
“Your absence"   
And a final punch to the groin

Two flashes of silver   
Cold sharp steel   
Glinting in its own light   
“Death is a luxury to you   
And I’ll make sure   
That you beg for it “   
I was his canvas   
His palette blood red   
No curved strokes   
Only straight strokes   
On the wrists   
On the chest   
On places left unnoticed   
And as a final touch   
The canvas was punctured   

“Keep this in your head   
The best gift   
That you can give   
To everyone around you   
Is your death”   
Were the last words   
That entered my ear   
As a loud bang   
Filled the room   
And a bullet of lead   
Filled my head   

‘twas not the end of it   
My eyes open   
And I’m back where I was   
A fresh canvas   
Only this time   
A fresh grill   
As he comes back    
With burning iron   
Death is a luxury   
That i shall have to beg for.   
Screams echoed   
And then it was over

The next day came   
And so, did he   
Faceless     
Relentless   
Merciless   
Brass glinted    
Knuckles clenched   
As he walked freely   
A gift that I missed   

“Look what you did   
You gave everything   
Every drop of what you had   
For one person”   
Brass met flesh   
“They don’t need   
Your support   
Your time   
Your effort”   
“They”   
Brass to the head   
“Are better off”   
Brass to the chest   
“Without you”   
Again and again   
Until the flesh   
Was tender as   
A newborn child   

“I understand you”   
A tiny voice   
Squeaked   
The sound a novelty   
In the harsh dungeon   
My mouth dared   
To say three words   
No response   
Was heard   

“I know that   
You care   
Enough to show up   
Everyday nonstop”   
My bravery was idiotic   
But the worst outcome   
Was a luxury to me   
“Only one   
Can care so much    
And I love you”   

The shadow over his face   
Slowly faded   
And I stared at myself   
Tears fell from his eyes   
His mask of shadows   
Fallen to the ground   
Brass tinkled as it fell   

“I just don’t want   
To see you get hurt   
Over and over again   
By giving so much”   
A warm tender voice   
Replaced the   
The piercing cold voice   

“I know now,   
And it’s all right   
Love will hurt   
That is a constant   
But I need you   
When things fall apart   
To remind me   
To take a moment   
To love you   
So I can love myself”   
I whispered   
As he came forward   

“I have always wanted   
not to hurt you   
but to have   
a faint trickle of your love”   
The words were lost   
In streams of tears   
And a warm embrace   
The dungeon was no more.   
For a place of torture   
Was no longer needed   
To ask yourself   
For a moment   
To love yourself   


