---
title: "700 words for 7 days at 7 AM"
description: |
  A small experiment
author:
  - name: Janith Wanniarachchi
date: "2025-02-08"
---

# Day 1: Ponies and Lies

_Straight away, I recognised the woman doting on her children as the bully from my high school._ I lowered the rim of my bucket hat hoping she wouldn't see my face. Two girls were sitting beside her both of them wearing shorts and "My Little Pony" t-shirts. Seeing the logos on their tees brought a visceral memory to the forefront of my mind, where I could see Brittney, my high school bully, munching on her gum while looking over her shoulder at the cover of my diary since I was a little girl.   
"Ew, you are still into those cringey ponies. Grow up bitch. Putting stickers on that stupid book won't hide the slutty things you are writing there, you fat whore" She scoffs as she walks away with her entourage. At the same time, I stare frozen on the spot noticing everyone's waves of laughter and wrinkled nose and brow magnified to an overwhelming state. The vision cuts to me in an unknown bathroom with tears in my eyes as I breathe in short gasps after Brittany's boyfriend Josh tried to grope me jeering "I heard from Brittany that you would be a good slut for anyone". And the vision settles into me in my bedroom writing into my diary, with tears staining the pages, "Why does everyone call me a slut when I haven't even held a guy's hand before?"    
It has been 20 years since I survived Brittany's reign during high school. And yet, I still froze on the spot when I saw her, half expecting her to look at me and start cackling at me with her daughters, pointing and laughing at me. I wasn't sure whether it was the run I just did or the series of visions that made me out of breath. Either way, I had to take a deep breath and rest my palms on my leggings to calm myself down.     
"I think that's enough running for today," I say as I tap the end on the smartwatch noticing that the distance was a metre shy of 5 kilometres even though I felt like I ran a lot more. My pace was at a moderate 5 minutes and I knew it needed to be improved a lot more if I was going to secure first place in the annual regional marathon after getting second place three years in a row.    
I tear my eyes away from the scene in front of me. "Mommy, mommy look my shirt is shining" I hear a little girl's shrill excitement from behind me. I peek behind my shoulder and hear "Aw that's beautiful sweetie, these ponies were mommy's favourite friend throughout mommy's life too, aren't they beautiful". I whip my head around to look back at Brittany and her daughters to see her giggling with her daughters sharing their joy of the ponies glinting in the sunlight.    
"I could settle this once and for all. I am an adult now. I do not have fear her any longer" I whisper to myself as my hands curl into fists. I walk up to Brittany and stand in front of her and her daughters blocking the sunlight falling on their faces. For a moment she looked puzzled at me squinting her eyes to look at who was standing in front of her.     
"I'm sorry do I know you from somewhere 'cause you look familiar." She cocks her head to the side with a bemused look.    
"Glad to see that you are finally owning up to enjoying My little pony, after bullying me for so long. How would you feel if your kids were called fat whores and groped at parties? Did you even think about how much it would affect the people around you?" The words flow from my mouth as if I was possessed by angry spirits that were sealed shut in a tomb for ages.   
"Oh..., Oh dear. You must have confused me for my twin sister. Are you talking about Brittany?" Her face darkens and the corners of her lips draw down in a sign of mild sadness.    
"Oh my god, I'm so sorry. I thought you were Brittany, I'm really sorry" My palm wraps around my mouth as I look at the entire face again in shock. I had recognised parts of her as my high school bully but there are subtle changes in her nose and ears that somewhat pointed to the alternative.    
"That's all right, it happens all the time. I don't think you heard the news I suppose? Yeah, you wouldn't be yelling at a random woman on the streets if you knew I guess. Brittany passed away a few months ago." She grimaced as the words left her mouth.   
The palm resting on my mouth clasped tighter as I took in a deep breath. "Oh my.. what happened? I'm so sorry I didn't know that happened."   
"It was sudden for us too. She had eloped with this drug dealer a few years ago. The only time we heard anything about her was when her body was found in a gang war site where two rival cartels had a shootout. It was shocking for us too." She said with a solemn grace and looked down.    
The story seemed outlandish but as I pieced together Brittany's dating history, it all seemed to make more sense.
"I'm absolutely stunned to hear that. I'm really sorry again for the confusion" I say as I select my words with caution. It was hard going through what Brittany did to me. At the same time, she did not deserve to die in such a tragic way. "I should get going back home. I will drop by later to properly offer my condolences." I mutter as I turn away from the scene for the second time.   
"That's all right sweetie, you don't have to really" She smiled weakly and stared into the distance.
I could not muster the energy to reply back so I decided to slowly trudge my way back home.   
"You did good sweeties, both of you didn't speak while mommy was talking to an adult" I could hear Brittany's sister cooing to her daughters as I walked by.    
"But mommy your name is Brittany isn't it?" The youngest daughter asks loudly from the edge of the seat.   


# Day 2: The cycle goes on

_Nervously, she opened the door to the abandoned house._ The door creaked forward on rusted hinges and the golden light from the evening sun flowed into the house. Standing at the doorway, she saw a narrow passageway that stretched out beyond the safety of the light and two large doors on either side of the entrance. Taking a deep breath of the mouldy stale air she patted around in the dark around the edge of the doorframe to find a tiny switch. Flicking it on did nothing however as the passageway was still only illuminated by the sun behind her. She sighed with an audible "Oh dear" and fumbled around in her purse to find her mobile. Flipping open the tattered leather case she presses on the small button on the side, the center and the two buttons that are connected together. But the screen remained pitch black. "Must be something wrong with these phones." she grumbles as she shoves the phone back into the purse. With a shake of her head she steps forward, and closes the door behind her. The darkness engulfed her with only a strip of light visible far away at the bottom of the passageway. She could not see clearly from where it was coming from and with heavy steps of foot and wood, she limped forward with her cane to the source of the light.    
The light was spilling from under a door on the side of the passageway. From behind the door faint music was being played and she could a voice having a rushed conversation in a language she didn't understand. She reached for the door knob and twisted it to realise the door was locked. As soon as she twisted the door knob the conversation stopped and the music faded away. "He doesn't want to be disturbed I guess" she thinks to herself "Must be busy with studies and catching up with his family back home". After a while the music and the conversation flowed again and so she turned around to walk back to the front of the passageway where she knew the living room would be at.     
From the tiny slivers of light creeping into the room from the blinds on the windows she could make out the outline of the couch she usually falls asleep in. Slowly after lowering herself on to the couch she puts her cane away and grabs a blanket from the nearby chair as she gently lays down on the sofa with the blanket wrapped around her. A slight cough crawls in through her throat and one after another several long drawn out coughs kept piling in. With each cough she could feel her heartbeat waver and settle, and once her breath settles she gently closes her eyes to fall asleep.     
When she opened her eyes again she was at the doorway to this house. Nervously, she opened the door to the abandoned house. The door creaked forward on its hinges and the golden light from the evening sun flowed into the passageway. Stepping into the house she closed the door behind her as usual knowing that none of her light sources were there and that she would have to rely on her memory of the place. Looking around she could see that the sliver of light at the bottom of the passageway has opened up. The light from inside the room has spilled onto the passageway illuminating the entire house with a tiny soft glow. "Wonder what he must be up to" she thinks to herself as she steps forward to the light. At that moment the door to her left opens up and a boy in her mid twenties steps out and walks past her. He did not acknowledge her presence and simply walked forward towards the light. "Must be busy as always working on his studies" she smiles and walks over to the couch in the living room to her right. She lies down on the couch keeping the cane to the side.    
As the line of coughs began to creep in she could hear from afar the boy talking loudly. "Gosh mom you wouldn't believe how bad this house is, even after grandma passed away I can still smell her horrible old smell around the house. Like right now even I smelled it near the doorway. I don't know how long I can keep staying at this hell hole with doors being opened randomly and broken switches being flipped on randomly."    
When she opened her eyes again she was at the doorway to this house. Nervously, she opened the door to the abandoned house.    

# Day 3: Love and Fate

You never know who you'll bump into at a funeral. The words of my best friend were stuck in my head as I looked at the scenery of the countryside passing behind me. There is no possible reality where this funeral would be eventful. It was saddening to hear that Grandma passed away unexpectedly when she was getting excited to celebrate her birthday next month. I was at my workplace near dozing off when I received the phone call from my mom about the news. Since then it has been a whirlwind of packing and planning flights to arrive at my hometown. I was excited to sleep in my childhood bed after a long time but I was not enthusiastic at all about meeting my high school friends and close family. The houses started looming ahead of me as I realized how close I was to my destination. With a deep sigh I braced myself to the barrage of questions and supposed familiar faces I had to greet and recognize.
"It is quite sad to hear that she passed away, we were all excited with her to celebrate her 90th birthday party." A man who's face I could not recognize shook my hand while looking at me expectantly with solemn eyes. It was almost as if he was looking for a sign on my face showing how I too was excited about her birthday. "Yes it was hard to hear for us all as well. But I'm sure wherever she is, she would be still excited for everything the world has to offer". I smiled as the words flowed through my mouth as if I had practiced these eulogies beforehand. Truth be told, I did. I knew that everyone wanted to size me up and make me feel bad for moving out into the city after high school leaving behind most of my friends and family. They wanted to know if I still had an inkling of humanity and compassion left after moving to the big city. Truth be told, I did.
The man smiled widely bordering on ingenuity and moved along to talk with couple other colleagues he saw near the bar. My grandma always being the one to make things interesting had specifically requested alcohol to be served at her funeral in her will. As I scanned the bar area, I think my grandma knew what would soothe our family more than I would have been able to.
"Yoo, it's been a long time man, Justin right?" A deep voice came from the right side of me and I turned to come face to face with a tall muscular man who was offering his hand as an invitation for the 'bro hug' as they call it. " We were in the same class in high school, you remember right? I was the one trying to get that girl in our class from bullying you that one time. What was her name" He laughed and patted my back as we disengaged from the hug. For a solid second I was lost in a sea of memories. 
First came an image of a young girl with long black hair and deep brown eyes that would take anyone's breath away, at least it did for me. Lizzie was her name and the frown on her brow and the wrinkles on her nose indicated to only the disgust and loathing that she felt when she saw me. The reason for those emotions, I have never known, but I could only assume they were because I looked not that attractive and somehow I managed to be put in to the same class as her all through out highschool. Every year, friends would shuffle around between classes but for some god's entertainment I was kept in the same class as her every year. She would always be getting first place in her studies while I would be at the second place no matter how hard I tried. 'Fugly Justin always ending up burnt by Lizzie's sizzle' was the term that was spread around high school and she made sure that her sizzle would include a barrage of scoffs induced descriptions of my looks and my nerdy nature.
"Yeah I remember you clearly bro." I clearly did not. "Thanks to you it was a lot easier going through the last year with Lizzie going a bit extra for some reason on the bullying" I smile back politely pulling myself out of the memory lane that I was trapped in. "Haven't seen for a while now, hope she's doing okay". I mumble with a smile as a contribution to the conversation.
"Well yeah she went through some tough times with her divorce after the jerk of her husband cheated on her. We haven't seen her in ages and I doubt she would be here either" The man who's name I should know looked around as if he was hoping to find her among the crowd. "Anyways smell ya later bro. You have become hella ripped since you left high school man, you should tell me your workout routine someday. Fugly Justin looks like should be now called Fuck boy Justin haha" he walked away laughing at his own twist to the joke.
"I sure hope not to find her here today. I don't think I can handle interacting with her today." I sigh and relax my shoulders from the tension I had endured.
"Justin? Is that you?" The familiar female voice seemed like an echo from the memories that I witnessed. I whip my full body to the side to come face to face with the same deep brown eyes that I fell in love with all through out highschool. "Lizzie?" I croaked.

# Day 4: Two masks

_She was beginning to realise how far down in her memory she'd buried her teenage years._ It has been years since I last saw Justin and for a split second she couldn't recognize him until she overheard his name being mentioned by the man in front of him.
"Coming to this funeral was a mistake." She sighed deeply and tried to relax her shoulders. After leaving high school she has tried her best to forget the horrible person she was during high school and find ways to forgive herself and move past it. But seeing the most consistent victim of her unstable teenage brain standing here made her feel sick in her stomach. Every time the memories of her teenage years comes up in her mind she would wince in pain and try to shove the thought carrying the memory away with every will power that she has. She knew that in reality confronting these thoughts and making peace with them is what needs to be done. What better place to start than the one person she annoyed consistently through out the years. The one person she started having feelings for because of his core values, despite him not fitting in with the stereotypical teenage boy.
Mustering up all the courage she had, she stepped closer to Justin after the other man had left, making sure he wouldn't see her approaching him. "Justin? Is that you?" she whispered the name that had haunted her dreams ever since leaving high school. Justin spun around and looked at her with such intensity that she had to take a step back. 
"Lizzie?" he said in a barely audible voice with a look of fear and horror written all over his face. "Hi uhh, I didn't expect you to be here. Not that I don't want you to be here. I do want you here. Not that I was planning on seeing you here. It's nice seeing you here. Not that it's nice only because you are here. Uhhh..." He rambled on in a flurry of words that Lizzie could not even keep track of. 
"Did he say that he wanted to see me? That can not be. Who in their right mind would want to see the one person that made their life a living hell for three years?" As the thoughts whizzed past Lizzie's head, she pulled a mask of decency and composure and spoke calmly "Yeah it's me Lizzie, it's nice seeing you back again Justin. How was the time spent in the city after leaving high school?". Even though the voice leaving her mouth was calm and composed, deep inside she was struggling to keep back from yelling how sorry she was for all the hell she let loose on him. 
"Oh yeah the city life was a bit hectic but I'm getting used to it now. What about you? How have you been doing since leaving high school? I didn't hear much about you either." His face instantly became composed the same way that she did and the words flowing through him were calm. It was the same technique that she used when she was feeling overwhelmed, she noticed that immediately.
"It's been all right. Been working in on some project management work and it's been smooth sailing. I didn't get around to meeting other people for a while because I was busy setting up my career." Lies. All lies. She knew perfectly well that she couldn't meet up with anyone because there was no one to meet up with that would forgive her behavior. The only friends she had were deep into some messy business with their boyfriends getting into drug dealing businesses. But after working in the corporate world she learned the right way to talk to people without showing her cards.
He took a deep breath and sighed before saying "I don't know if this is the right place to say this but would you be interested in having a cup of coffee tomorrow. I was planning on running in the morning and I would love to catch up with you tomorrow after that". He smiled faintly and for a moment Lizzie wanted to scream out yes and hug him tight the same way she day dreamed of when she was in high school.
"Yeah my calendar should be free tomorrow." There was no calendar to check up on. "I am also taking up running these days and can join with you for the run tomorrow." she had never physically run a mile in real life, aside from running away from the memories of her teenage years. The only form of physical exercise she had was the yoga that she did at home while watching a Youtube video.
"Oh wow that would be great" There was a small crack in his composure as a sliver of genuine excitement came to his face. Lizzie was not sure if it was real or if her mind was drawing illusions on his face. "I will be starting off from the church and it will be an easy 5K run around the running pathway."
She smiled widely to hide the panic of running 5 kilometers for the first time with no prior training. "Great I will see you then".

# Day 5: Pride run

_In the middle of a crowd, he felt a tap on his shoulder._ He turned back to see the familiar face he was expecting to see near the church when he arrived for his morning run.
"Heyy, sorry about the delay. Got a bit late getting ready for the run today." she smiled as she looked at him intently. His eyes quickly darted to check her attire and rested on her eyes once again. She was wearing a gray pushup bra with tight leggings and her black hair was tied up in a ponytail behind her. For all his time in high school he had never seen her in this attire and he was thankful that he didn't get to see it during high school. Otherwise he would have fallen harder for her and it would have been even more difficult for him to let go of this place and move to the city to continue his studies. 
"That's all right. There's no fixed time to start running so we can start anytime we want. Shall we start with the warmup then?" he asked as he moved to the side of the track lifting his knee to his abdomen. 
"Yeah for sure, warmup is crucial yes." he heard her whisper in a soft tone as she mirrored his stance in front of him. Her face did not speak of any emotion and she stared on to the distance as she followed the warmup routine that he was doing.
"Lovely weather for a run today. And it's a lot more spacious here than the city."
"Yeah I would assume so"
"The leaves are turning golden slowly, ready for the fall season it seems"
"It looks that way, yes"
"I will miss these when I have to leave back to the city in another three days time."
"WHAT??" 
He was taken aback by her abrupt and loud response. "Yeah why not, I could get leave only for a few days since it was my grand mother's funeral. Have to get back to work again after settling the family matters." He shook his head as if to dust away the clouds of worry that gathered at the horizon every time he though of having to go back. 
"Oh... yeah that makes perfect sense. You would need to get back to your workplace to do..." She frowned and looked at him straightening herself from the hamstring stretch. "Forgive me if I'm being rude, what exactly is it that you are doing in your job? We all knew you went  to the city to study something related to fashion I think"
"Well yes it was to study fashion and right now I'm the lead designer in a team working on women's sport wear, these days we are working on a project to make comfortable and breathable running tops." He smiled while making sure to look directly at her eyes. He wanted to know badly what she thought of his position. For a split second (or did he imagine it?) she furrowed her brow and a slight pout formed on her lips. But within the next moment her face was back to the usual composed blank slate that she held for so long. It was almost like she didn't want to show her true emotions.
"That's great to hear. I'm sure you must be doing pretty amazing work at your job." She said with a smile. "Perhaps someday I can try out the sports wear that you made for my running sessions". She looked far away into the distance as if she was picturing that moment. 
"Well if you do want I think I have one sample that I wanted to see if the final material fit well to the specifications we gave. I mean if you are comfortable with doing that. I can pay you the same rate we pay our models if you want." He said quickly and looked down in embarrassment. 
"No thank you. I'm not some bimbo for you to try clothes and ogle at." She said sternly with squinted eyes. "Shall we get to this run of yours?" She said stepping on to the track.
"Yes yes we shall" He said with a sigh and began running with Lizzie following along.
A few minutes passed and his watch indicated that he had reached 2.5 kilometers in his run. He looked back to see how Lizzie was doing but she was nowhere to be seen for a long distance. He quickly ran back along the track looking for her and after running for another 10 minutes or so he found her on the side of the track holding on to the trunk of a tree. 
"Hey are you all right" As he ran closer he could see that she had thrown up on the side of the road and was holding on to the tree panting heavily.
"Yeah I'm all right, you continue on the run, I will join you someday later. I think I will be heading home after cleaning myself up and the mess I made here. Thanks for the invite to the coffee but I will have to get a rain check on that." She said without looking up at him in the most calm composed tone she could muster.
"That's fine I can stay and help out. The coffee wasn't a big deal." 
"I think I made myself clear that I want to head home by myself. I would prefer it if you didn't cross that boundary right now."
"Yes yes of course I understand. Sorry about all this Lizzie, hope you feel better soon." His flurry of apologies triggers him back to his old memories where he apologized for his appearance to Lizzie when she mocked him infront of others. "I will be needing some time alone by myself after the run as well. See you around, it was nice catching up with you."
"I didn't ask what you were doing after the run. Take all the time you need and leave back to the city once you are done with your stay here. It was nice catching up with what you were doing back in the city" She said with a grim tone and kicked the dirt around to cover her mess while heading to the water fountain to clean herself up.

# Day 6:

_With sadness, she realised they needed some time apart._ She came to this realization as she opened the door to her home. After the embarassing scene back near the running track where she nearly threw up her insides, she decided it was best to call it at that point and come home. The obvious truth was that she has never run properly in her life and as she tried to keep up with Justin's running speed her heartbeat climbed up faster than she could and the longer she tried to push her body forward, the more her body resisted and screamed in protest. 
Adding on to the embarassment was the feeling that was going inside her. She was sure what the feeling was but she could not come to terms with how childish she was. The feeling of jealousy that Justin is surrounded with models wanting to try the clothes that he had made. How childish and stupid was she thinking. Only a boy would think this way  she thought to herself as she took stepped into the washroom to clean herself after the run. 
After cleaning herself up she fished out her pre made breakfast of yoghurt and oats with berries to start off her work day. She couldn't shake off how childish and especially immature her mind was earlier. Her distracted mind drove her to open up her socials in between meetings, reenforcing a habit that she wanted to get rid of. After numbing her brain with endless amount of teenagers dancing and cats falling backward as a slice of cheese fell on their head, she was about to get back into her work when she noticed a new message request had popped up on her notifications. She was sure it was some random dude with a big burly moustache or a profile picture of an anime character saying 'Hi'. The day was ruined by this point so I might as well indulge myself with the newest challenger to the ring, she thought as she clicked the notification and her eyes grew large as she read the name that had messaged her.
Justin Stewart: Hey, I hope you are doing all right after the run this morning. I'm really sorry ...
The rest of the message was cut off with the limited preview space but her curiosity was already drawing out possible replies. Checking the time she realised there's more than 4 hours to go in her workday. Also she didn't want to appear too eager even though technically Justin wouldn't be getting a read receipt until she replies back. 
After trudging through 4 hours of mind numbing she finally was able to sign off from work as she ceremoniously closed the laptop off. Moving from one screen to another, she quickly opened up her phone to check the apology from Justin. For a split second, she froze as she caught herself feeling the surge of emotions she felt back during high school watching Justin take in her mocking, only this time there was no crowd to witness and watch in awe at her prowess. "Damn it, this mindfulness shit from therapy is starting to work now" She cursed as she took a deep breath and detached herself from the past memory.
"I'm not in high school anymore where I need to win everyone's approval to stay valuable."
"I'm not in my childhood home where my dad wanted a son so being rough and mean was the only way to win his affection"
"I'm not my past self. I'm guilty but I will not bully myself for the mistakes I have done"
She muttered the phrases that her therapist had recommended while breathing deeply. When she first started therapy, her therapist told her to say these out loud even if she didn't feel like it, and now she's slowly starting to realize its effectiveness. 
After making sure her head was in the right place she opened the message to view Justin's message.
Justin Stewart: Hey, I hope you are doing all right after the run this morning. I'm really sorry if I said anything hurtful to you, because you seemed pretty upset when you told me to go back to the city. I was wondering whether you would be free to have some food at the Italian restaurant near my house. It's on me, consider it a token of apology for whatever I did wrong to you. Also it seems that I will have to return back to the city sooner than I thought because it seems my wife has fallen sick and I will have to go see her soon.
Her heart fell as the she read the last line. Not because she cared for the wellbeing of Justin's wife but the mere existence of her caught her by surprise. It shouldn't be a surprise shouldn't it? Everyone deserves love. Long lasting committed love. Unlike her recent divorce with her cheating husband.