---
title: "The waitress"
description: |
  A poem written while in a coffee shop watching the waitress serve tables
author:
  - name: Janith Wanniarachchi
date: "2024-02-13"
---

The dim light on the ceiling   
casting shadows of countless faces   
that she served, that she smiled at,    
as she lifted another tray   
of overflowing cups and plates.   
The dim light of the ceiling    
fades away   
only to be replaced, with a bright spotlight.    
She no longer was a waitress in green.   
She was the centre piece    
of the most intricate juggling act.   
Beneath her was a web of tangled strings   
as she cycled on a unicycle   
with heavy pins flopping through her hands.   
At the end of each strings    
was every facet of her life    
trying their best to steal the spotlight.   
Nevertheless she persisted.   
With a smile that she managed to conjure 
She asks, "Is everything all right on your table?"   
and I lied   
The same lie that we tell each other    
"Yes everything is all good here"    
while my heart screamed out    
"I'm proud of you, it's going to be all better soon"   
