---
title: "A tale of two lovers"
description: |
  A tale of two lovers entwined in a dance of their own minds
author:
  - name: Janith Wanniarachchi
date: 2020-07-15
---

It all began   
with a blink of an eye   
The spotlight was on us   
All eyes were set on us   
One glance in your direction   
The smile on your face   
The breath in your chest   
Your outstretched hand   
before the leap of faith   

And so it began   
You were the ocean   
wild and untamed   
with your slender hips   
creating wave after wave   
with every step you took   
A white top on your chest   
and a blue bottom on your hips   
blended together   
with a skin of deep brown   
a perfect rendition of a wave   
the foam of the wave   
the deep blue sea   
the murky brown held within   
An image that even 
the daughter of Poseidon   
wished she could adorn   

And so it began 
I was the beach   
steady and firm   
holding to you   
creating an anchor   
for your beauty to bless the stage   
as your grace went from one end to another   
while having a home to rely on   
Dark skin with a clear cut landscape   
with the bountiful belly of the land   
and bronze clothing   
a perfect rendition of the beach   
a image that your heart yearned for   

we were upon each other   
pushing and pulling 
slightly on the edges of our finger tips   
firmly on the bends of our elbows   
pushing and pulling   
and those in front   
watched in awe   
as the waves came and lapped against the beach   
teasing and seducing 
but never explicit   
sensually bringing one another close   
and each moment 
the waves and the beach met   
I was in heaven   

The smell of your luscious black hair   
Lined with the musky fragrance of your body   
With each spin your hair graced my skin   
At times it was a playful whip   
At times it was a warm velvet   
Holding your lithe figure 
Close to me   
even for a second   
made me complete   

The lights were dimming   
and just then you smiled   
and my whole world became brighter   
we came together   
we saw the world together   
we had conquered   
the stage   
and their hearts   
and our fortresses of love   
together   

It all went on   
With a blink of an eye   
The moonlight was on us   
No eyes were set on us   
One glance in your direction   
The smile on your face   
The breath in your bare chest   
The dazzling beauty 
of your bronze skin   
painted in silver under the moonlight   
before the leap of faith   

And so it began   
You were an ocean 
A fountain of youth   
That I always craved for   
Each time I bathed my face in it   
I felt a thousand years younger   
And I felt more and more   
closer to heaven   
as I could hear the name of God himself   
escape from your mouth   
You were an ocean   
spontaneous   
unpredictable   
One moment I would look down at the ocean   
and the next I was overwhelmed by it   

And so it began 
I was the beach   
transitioning 
from softness to hardness   
as the waves 
came roaring in   
towards the land   
and slowly made its way downward   
ending in a milky white froth   
Before long 
the waves crashed again   
on to the groin of the beach   
one after another   
wave after wave   
until the waves and the beach   
could no longer ride the flow   
and became one   
as they were meant to be   

The lights were dimming   
and just then you smiled   
and my whole world became brighter   
we came together   
we saw the world together   
we had conquered   
our home   
and our hearts   
and our fortresses of love   
together   
