---
title: "Inspiration can be painful"
description: |
  Short poems mourning a spark of inspiration that has been lost 
author:
  - name: Janith Wanniarachchi
date: "2024-10-03"
---

# A wail of loss

I still love you   
And I wish   
with all the remnants of my broken heart    
that there was something   
I could do to do   
Bring my love to you   

I would be the modern day 荀奉倩   
Giving it all I could   
To make you happy and satisfied   
To hold you tight in the coldest nights   

But alas   
No matter what I feel   
The world will keep spinning   
C’est la vie, mon cœur   
Je t’aime pour toujours   

# What does it mean to be loved?

Her eyes were the brown of the fresh spring soil,   
from which sprang the tulips of pink, the same shade as her lips.   
And as I looked at her with a smile of a day dreaming fool,   
she smiles and asks   
“How do you want to be loved?”.   
And at once a symphony of voices began whispering in my ear!   
Of dreams and fantasies,   
Hopes and aspirations!   
The more i listened   
the chorus of all my voices became clear,   
“… with you by my side”   
And with all the courage I had   
I whispered   
“Stay with me”.   
And as she sat closer   
I realized what it is to be loved…   

# A glimmer of a hope 

අමාවක රැ අහසේ   
තනි වි අතරමං වු   
මාගේ නිවී ගිය පහනට   
එළිය ගෙනා   
අමාවක රැ අහසේ   
තරු රටාවක සැගවි   
සිටිය මාගේ ප්‍රියාවියේ   

මාගේ පහන් එළියෙන්   
දිළෙන ඔබේ දෙනෙත් තුලින්   
ඔබේ හදවතට කිමිදුන මා   
කෙසේද ඔබව අමතක කර ඉන්නේ   

මසකට වරක් එන   
අමාවක අහසක   
තරු රටාවේ සැගවි ඉන්නා   
ඔබව දැක   
ඔබේ දෑතේ ඇගිළි අතරේ පැටලි   
ඔබේ දිලෙන දැසින් ඔප දැමු   
ඔබේ මදහස තුලින්   
මගේ නිවි ගිය පහන   
එළිය වෙන දින එන තුරා   
මගේ හදේ   
ඔබේ මතකයන්   
සදා රැදි තිබෙවි   

