---
title: "Those who weave the prettiest dreams"
description: |
  A short story dedicated those who weave the prettiest dreams
author:
  - name: Janith Wanniarachchi
date: "2021-05-12"
---

“Imagine you are opening the lock on your brand new home and coming in after a long day of work to see the house all cleaned up nicely. The love of your life, the perfect man for you, is in the kitchen making dinner with the two children and having a grand time.” Said the fairy god mother to the girl on her bed. 

The girl wiped the tears from the bloodshot eyes. “Stop, stop, please, those stuff used to give me the happiness I needed, but I have been run over by life to know that none of it is going to be true.” She stammered and curled up into a ball, hugging herself. 

“Well sweetie, I’m just a fairy god mother that’s part of your imagination. I’m not a genie to give you all that you want, goodness me, and people who believe that their problems can be solved by genies are the worst of them all. So ungrateful, I tell you.” The fairy god mother frowned and shook her head in disbelief. 

“I don’t want to hear about other people! Can’t you see I’m in pain. Life hasn’t given me anything to be happy about. I’m miserable and desperate and that’s why I called you for help. Please can you focus on me for one second.” She broke into tears again as she stammered those words from her mouth. The fairy god mother looked at her with concern in her eyes, her shimmering wings fluttered softly, a clear sign that she was under pressure. 

“What can I offer you? Other than my words of a world where things would be better. I can tell you how good the light at the end of the tunnel is, but only you know where you want to make the tunnel end. Once I was the best thing that ever happened in your life, and now I am nothing more than an evil liar, a cunning manipulator, who simply lulled you into a trap of fake reality.” The fairy god mother sighed and let her wings relax. 

“I did what I could do, I’m only a part of your imagination, so close yet so far away from you, a presence that can only be felt but never seen or touched. I can still assure you that there is still hope left to fight for, that there is some good in this world to live and take another step. But it’s much easier for you to just give in and curse the entire world.” She got up from the girl’s bedside and walked towards the window. “If ever you need to feel hope in this world, call my name and I shall be by your side, but to turn that hope into a reality, you need to get out of that bed and wipe those tears away.” 

Turning around, the fairy god mother saw the anger in the little girl’s eyes. “Go! Go away then! Leave me as everyone else does! You were a liar all this time. You just wanted to manipulate me and keep me in place. You wanted to use me to feed your ego! That was all that you were, nothing more.” The little girl screamed from on top of the bed with hot tears streaming down her face. 

“Those who weave the prettiest dreams are the ones who are hated the most when it’s time to wake up” And with a slight breeze the fairy god mother was gone, and the little girl was left with her broken heart. 